from gymnasium.envs.classic_control.acrobot import AcrobotEnv
from gymnasium.envs.classic_control.cartpole import CartPoleEnv
from gymnasium.envs.classic_control.continuous_mountain_car import (
    Continuous_MountainCarEnv,
)
from gymnasium.envs.classic_control.mountain_car import MountainCarEnv
from gymnasium.envs.classic_control.pendulum import PendulumEnv

from gymnasium.envs.classic_control.custom_env_2d_sensor import SensorEnv2DSimple
from gymnasium.envs.classic_control.custom_env_2d_sensor_evaluator import SensorEnv2DEval   # TODO: remove it

from gymnasium.envs.classic_control.custom_env_1d_sensor_simple import Sensor1DEnvSimple
from gymnasium.envs.classic_control.custom_env_1d_sensor_shuttler import Sensor1DEnvSimpleShuttler
from gymnasium.envs.classic_control.custom_env_1d_sensor_with_mu import Sensor1DEnvSimpleWithMu
from gymnasium.envs.classic_control.custom_env_1d_sensor_shuttler_2gauss import Sensor1DEnvSimpleShuttler2Gauss
from gymnasium.envs.classic_control.custom_env_1d_sensor_shuttler_N_gauss import Sensor1DEnvShuttlerNGauss
from gymnasium.envs.classic_control.pattern_tracking import PatternTrackingEnv